### ISSUE TITLE
Content Security Policy | sources.join is not a function

### ISSUE THREAD

**Issue by markus-gx** [Baroshem/nuxt-security#133]
### Version

nuxt-security: v0.13.0
nuxt: 3.2.3

### Steps to reproduce
Adding or upgrading to the latest version of nuxt-security. 

### What is actually happening?

```
[error] sources.join is not a function
9:54:45 AM:   at node_modules/nuxt-security/dist/module.mjs:108:57
9:54:45 AM:   at Array.map (<anonymous>)
9:54:45 AM:   at Object.contentSecurityPolicy (node_modules/nuxt-security/dist/module.mjs:104:34)
9:54:45 AM:   at getHeaderValueFromOptions (node_modules/nuxt-security/dist/module.mjs:117:42)
9:54:45 AM:   at setSecurityResponseHeaders (node_modules/nuxt-security/dist/module.mjs:223:44)
9:54:45 AM:   at setup (node_modules/nuxt-security/dist/module.mjs:152:7)
9:54:45 AM:   at normalizedModule (node_modules/nuxt-security/node_modules/@nuxt/kit/dist/index.mjs:169:41)
9:54:45 AM:   at async installModule (node_modules/@nuxt/kit/dist/index.mjs:435:15)
9:54:45 AM:   at async initNuxt (node_modules/nuxt/dist/index.mjs:2256:7)
9:54:45 AM:   at async loadNuxt (node_modules/nuxt/dist/index.mjs:2289:5)
9:54:45 AM:   at async loadNuxt (node_modules/@nuxt/kit/dist/index.mjs:522:19)
9:54:45 AM:   at async Object.invoke (node_modules/nuxi/dist/chunks/build.mjs:34:18)
9:54:45 AM:   at async _main (node_modules/nuxi/dist/cli.mjs:50:20)
```

**Comment by Baroshem** [comment]
Hey @markus-gx 

Could you provide additional info like content of your nuxt.config file?

**Comment by markus-gx** [comment]
Totally missed it thanks.

**Comment by Baroshem** [comment]
Awesome, 

Glad I could help! 

Let me know if you encounter any other issues :)

**Comment by Harm-Nullix** [comment]
A minor bump with breaking changes, I like it 👍
