### ISSUE TITLE
Nuxt Security not working with Nuxt Bridge

### ISSUE THREAD

**Issue by Jesus82** [Baroshem/nuxt-security#207]
### Version

```
"nuxt: "2.17.1"
"@nuxt/bridge": "npm:@nuxt/bridge-edge@3.0.0-28232126.5c5bc70",
"nuxt-security": "^0.14.4"
```

### Reproduction Link

[Stackblitz](https://stackblitz.com/edit/nuxt2-17-bridge-false-ovlip2)

### Steps to reproduce
App doesn't start

### What is actually happening?

```
[9:54:04]  ERROR  Cannot start nuxt:  Cannot read properties of undefined (reading 'private')

  at setup (node_modules/nuxt-security/dist/module.mjs:156:34)
  at ModuleContainer.normalizedModule (node_modules/@nuxt/kit/dist/index.mjs:2220:37)
  at async ModuleContainer.addModule (node_modules/@nuxt/core/dist/core.js:167:20)
  at async ModuleContainer.ready (node_modules/@nuxt/core/dist/core.js:36:5)
  at async Nuxt._init (node_modules/@nuxt/core/dist/core.js:342:5)
```

**Comment by Baroshem** [comment]
Hey,

Yes that is correct. Nuxt Security works only with Nuxt 3. It is using route rules and new event handlers by H3 to handle that are available in Nuxt 3 only.

**Comment by Jesus82** [comment]
@Baroshem would be nice to include that in the Readme, as most Nuxt 3 libraries works with Nuxt Bridge.

**Comment by Baroshem** [comment]
I have included following in the Features for both documentation and the README.md:

```
## Features
* Nuxt 3 ready
* ...
```

Do you think it would be more informative to change it to `Nuxt 3 only`?
