### ISSUE TITLE
Error: cannot set headers after they are sent to the client

### ISSUE THREAD

**Issue by gregg-cbs** [Baroshem/nuxt-security#7]
Receiving a couple errors when using this module.
Any advice?
```
 ERROR

 6: import _EyMD21 from 'D:\Devbox\Dare\ms-amlin\code\node_modules\nuxt-security\dist\runtime\server\middleware\headers\referrerPolicy';
 7: import _dVKsGV from 'D:\Devbox\Dare\ms-amlin\code\node_modules\nuxt-security\dist\runtime\server\middleware\headers\strictTransportSecurity';
 8: import _A7rfIb from 'D:\Devbox\Dare\ms-amlin\code\node_modules\nuxt-security\dist\runtime\server\middleware\headers\xContentTypeOptions';
                                                                                                                         ^
 9: import _6AG9Sx from 'D:\Devbox\Dare\ms-amlin\code\node_modules\nuxt-security\dist\runtime\server\middleware\headers\xDNSPrefetchControl';
10: import _aR9QUI from 'D:\Devbox\Dare\ms-amlin\code\node_modules\nuxt-security\dist\runtime\server\middleware\headers\xDownloadOptions';
```

```
 ERROR  [unhandledRejection] Cannot set headers after they are sent to the client

  at new NodeError (node:internal/errors:371:5)
  at ServerResponse.setHeader (node:_http_outgoing:576:11)
  at sendError (/D:/Devbox/Dare/ms-amlin/code/node_modules/h3/dist/index.mjs:72:13)
  at nodeHandler (/D:/Devbox/Dare/ms-amlin/code/node_modules/h3/dist/index.mjs:550:15)
```

**Comment by Baroshem** [comment]
Hey hey, could you paste your `nuxt.config.ts` file here?

**Comment by gregg-cbs** [comment]
this is it:

```
export default defineNuxtConfig({
  meta: {
    charset: 'utf-8',
    viewport: 'width=device-width, initial-scale=1',
    title: 'MS Amlin',
    meta: [
      { name: "copyright", content: "MS Amlin" },
      { name: "description", content: 'MS Amlin is a leading insurer and reinsurer, and part of the global top-10 insurance group MS&AD. Our role places us at the forefront of the Property & Casualty, Marine & Aviation and Reinsurance markets. We deliver continuity for businesses facing the most complex and demanding risks. In turn, this promotes continuity and prosperity around the world.' },
      { name: "robots", content: 'index, follow' },
      { "http-equiv": "language", content: "en-GB" },
      { "http-equiv": "cache-control", content: "private" },
      { "http-equiv": "expires", content: "max-age=604800" },
    ],
  
    link: [
      { rel: "icon", type: "image/png", href: "/favicons/favicon.png" }
    ],

    "style": [],
    "script": [],
    "noscript": [],
    htmlAttrs: {
      lang: 'en-GB'
    }
  },
  
  "dirs": [    
    {
      "path": "./components",
      "global": true
    }
  ],

  modules: [
    "nuxt-security",
  ],

  vite: {
    css: {
      preprocessorOptions: {
        scss: {
          // additionalData: '@use "@/assets/colors.scss" as *;'
        }
      }
    }
  }
})
```

**Comment by Baroshem** [comment]
Hmm strange, is it dev or production environment? Also, what kind of rendering type? SSR or Static?

**Comment by gregg-cbs** [comment]
I have no packages installed other than sass and this one.

**Comment by Baroshem** [comment]
I see. Let me try it on my end and see if I can reproduce it.

**Comment by Baroshem** [comment]
This is really strange, I have just created a project with the same nuxt config as yours and it is working correctly. Could you please create a reproduction repository on Stackblitz or Codesadbox where the issue is reproducable?

**Comment by gregg-cbs** [comment]
Sure I will have a look at that today !

**Comment by Baroshem** [comment]
Thanks! I will do my best to help 🙂

**Comment by gregg-cbs** [comment]
After removing this from Nuxt I am still seeing the error. I am in discussion with the nuxt team on this.

**Comment by Baroshem** [comment]
Hey @gregg-cbs 

I believe that the issue has been solved. If not, feel free to reopen the issue so that we can work on it together :)

**Comment by gregg-cbs** [comment]
Thanks, I have still been seeing the issue, there is no way to know when or why it happens, just happens randomly, maybe after hotreloading. I will leave it for now thanks.
