### ISSUE TITLE
 returns undefined error on request (req)

### ISSUE THREAD

**Issue by GenerousWeb** [Baroshem/nuxt-security#71]
### Version

nuxt-security: >= 0.8.0 
nuxt: 3.0.0-rc.13

### What is actually happening? throws 500 error 
[nuxt] [request error] [unhandled] [500] Cannot read properties of undefined (reading 'req')
  at Object.handler (./.nuxt/dev/index.mjs:464:53)  
  at Object.handler (./node_modules/h3/dist/index.mjs:634:31)  
  at processTicksAndRejections (node:internal/process/task_queues:96:5)  
  at async Server.toNodeHandle (./node_modules/h3/dist/index.mjs:698:7)
[nuxt] [request error] [unhandled] [500] Cannot read properties of undefined (reading 'req')
  at Object.handler (./.nuxt/dev/index.mjs:464:53)  
  at Object.handler (./node_modules/h3/dist/index.mjs:634:31)  
  at processTicksAndRejections (node:internal/process/task_queues:96:5)  
  at async toNodeHandle (./node_modules/h3/dist/index.mjs:698:7)  
  at async Object.ufetch [as localFetch] (./node_modules/unenv/runtime/fetch/index.mjs:9:17)  
  at async Object.errorhandler [as onError] (./.nuxt/dev/index.mjs:436:30)  
  at async Server.toNodeHandle (./node_modules/h3/dist/index.mjs:705:9)
[nuxt] [request error] [unhandled] [500] Cannot read properties of undefined (reading 'req')
  at Object.handler (./.nuxt/dev/index.mjs:464:53)  
  at Object.handler (./node_modules/h3/dist/index.mjs:634:31)  
  at processTicksAndRejections (node:internal/process/task_queues:96:5)  
  at async Server.toNodeHandle (./node_modules/h3/dist/index.mjs:698:7)
[nuxt] [request error] [unhandled] [500] Cannot read properties of undefined (reading 'req')
  at Object.handler (./.nuxt/dev/index.mjs:464:53)  
  at Object.handler (./node_modules/h3/dist/index.mjs:634:31)  
  at processTicksAndRejections (node:internal/process/task_queues:96:5)  
  at async toNodeHandle (./node_modules/h3/dist/index.mjs:698:7)  
  at async Object.ufetch [as localFetch] (./node_modules/unenv/runtime/fetch/index.mjs:9:17)  
  at async Object.errorhandler [as onError] (./.nuxt/dev/index.mjs:436:30)  
  at async Server.toNodeHandle (./node_modules/h3/dist/index.mjs:705:9)

**Comment by Baroshem** [comment]
Hey, can you try version 0.9.0 of the module and stable version of Nuxt 3? Your issue seems to be releated with the fact that during one of the rc versions of nuxt, there was a change in how the req object is accessed

**Comment by GenerousWeb** [comment]
Thanks mate. nuxt-security@0.9.0 Works with nuxt@3.0.0-rc-14. 

Does this package support nuxt generate ?

**Comment by Baroshem** [comment]
No it does not. Nuxt generate will create a static website from your code and it will not involve server. nuxt-security is using server handlers and route roules which both need a server to work.

**Comment by Baroshem** [comment]
Closing the issue as the answer was given :)
